version: '3'
services:
  nexus-oss:
    image: "${NEXUS_IMAGE}:${NEXUS_VERSION}"
    user: "${UID}:${GID}"
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - "${PWD}/oss-nexus.properties:/nexus-data/etc/nexus.properties:ro"
    profiles:
      - oss
  nexus-pro:
    image: "${NEXUS_IMAGE}:${NEXUS_VERSION}"
    user: "${UID}:${GID}"
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - "${PWD}/pro-nexus.properties:/nexus-data/etc/nexus.properties:ro"
      - "${PWD}/license.lic:/nexus-data/etc/license.lic:ro"
    profiles:
      - pro
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
    command: "server --address :9000 /data"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
